# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
