"""empty message

Revision ID: 3933d2f212e4
Revises: 267672efcd07
Create Date: 2018-03-20 18:56:38.341188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3933d2f212e4'
down_revision = '267672efcd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_believable', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excuses')
    # ### end Alembic commands ###
