"""Adding messages table

Revision ID: 5244af6c8f58
Revises: e173c2f03dcc
Create Date: 2018-03-22 06:53:17.374816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5244af6c8f58'
down_revision = 'e173c2f03dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
